#!/usr/bin/python

from Controllers.Configuration import *
from Commands.Up import *
from Commands.Down import *
from Commands.Provision import *
from Commands.Rebuild import *
from Commands.Ssh import *
from Commands.Status import *
from Commands.Help import *
from Commands.Info import *

# Creates the Configuration object.
Configuration = Configuration()

current_path = Configuration.currentPath()
app_name = Configuration.appName()

if len (sys.argv) > 1:
    # Change dir to path where command is run
    os.chdir(current_path)

    if sys.argv[1] == 'up':
        Up.run()
    elif sys.argv[1] == 'down':
        Down.run()
    elif sys.argv[1] == 'provision':
        Provision.run()
    elif sys.argv[1] == 'rebuild':
        Rebuild.run()
    elif sys.argv[1] == 'ssh':
        Ssh.run(app_name)
    elif sys.argv[1] == 'status':
        Status.run(app_name)
    elif sys.argv[1] == 'info':
        if len(sys.argv) > 2:
            Info().getSingleContainerInfo(app_name, sys.argv[2])
        else:
            Info().getAllContainersInfo(app_name)
    elif sys.argv[1] == 'help':
        Help.run()
    else:
        print 'There is no command like that!'
else:
    Help.run()