#!/usr/bin/python

from Controllers.Configuration import *
from Commands.Up import *
from Commands.Down import *
from Commands.Provision import *
from Commands.Rebuild import *
from Commands.Ssh import *
from Commands.Status import *
from Commands.Help import *
from Commands.Info import *
from Commands.Application import *
from Commands.Restart import *

# Creates the Configuration object.
Configuration = Configuration()

current_path = Configuration.currentPath()
environment_namespace = Configuration.environmentNamespace()

if len(sys.argv) > 1:
    # Change dir to path where command is run
    os.chdir(current_path)

    if sys.argv[1] == 'up':
        Up.run(environment_namespace)
    elif sys.argv[1] == 'down':
        Down.run(environment_namespace)
    elif sys.argv[1] == 'provision':
        Provision.run()
    elif sys.argv[1] == 'rebuild':
        Rebuild.run(current_path, environment_namespace)
    elif sys.argv[1] == 'ssh':
        Ssh.run(environment_namespace)
    elif sys.argv[1] == 'status':
        Status.run(environment_namespace)
    elif sys.argv[1] == 'info':
        if len(sys.argv) > 2:
            Info().getSingleContainerInfo(environment_namespace, sys.argv[2])
        else:
            Info().getAllContainersInfo(environment_namespace)
    elif sys.argv[1] == 'restart':
        Restart().run(environment_namespace)
    elif sys.argv[1] == 'help':
        Help.run()
    else:
        applications = Application().getApplications()
        application_name = sys.argv[1]
        if application_name in applications:
            arguments = sys.argv
            Application().runApplication(application_name, arguments)
        else:
            print 'There is no command like that!'
else:
    Help.run()